version: "3.8"

services:
  rmqnamesrv:
    image: apache/rocketmq:5.3.1
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    environment:
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn128m"
    command: sh mqnamesrv
    networks:
      - rocketmq

  rmqbroker:
    image: apache/rocketmq:5.3.1
    container_name: rmqbroker
    depends_on:
      - rmqnamesrv
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn256m"
    volumes:
      - ./docker/rocketmq/broker.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    networks:
      - rocketmq

  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    depends_on:
      - rmqnamesrv
    ports:
      - "8088:8080"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dserver.port=8080"
    networks:
      - rocketmq

networks:
  rocketmq:
    driver: bridge
